dohs:
  - "https://223.6.6.6/dns-query"
  - "https://223.5.5.5/dns-query"
  - "https://208.67.222.222/dns-query"
  - "https://208.67.220.220/dns-query"
  - "https://120.53.53.53/dns-query"
port: 153
timeout: 60
# default: 3 days
enable_clear_expired_cache: true
clear_cache_interval: 259200
ttl_duration: 36000
resolve_skip_domains:
  - "epg.aptv.app."
enable_cache: true
