dohs:
  - "https://223.6.6.6/dns-query"
  - "https://223.5.5.5/dns-query"
port: 153
timeout: 60
# default: 3 days
enable_clear_expired_cache: true
clear_cache_interval: 259200
ttl_duration: 36000
resolve_skip_domains:
  - "epg.aptv.app."
enable_cache: true
map_init_capacity: 65535
map_init_shard_amount: 8192
enable_sniffing: true
ttl_range_multi:
  10: 10
  50: 8
  100: 7
  250: 6
  500: 5
  1000: 4
  1500: 2
  10000: 1
